[package]
name = "lazytypst"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
ratatui = "0.30.2"
ratatui-image = { version = "11.1", default-features = false, features = ["crossterm"] }
ratatui-textarea = { version = "0.9.2", features = ["search"] }
